version: '3.8'

services:
    mongodb:
        container_name: mongodb-api-whatsapp
        image: mongo:latest
        restart: unless-stopped
        ports:
            - 27777:27017
        volumes:
            - db:/data/db
    app:
        container_name: api-whatsapp
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=${PORT}
        depends_on:
            - mongodb
        restart: unless-stopped
        env_file: .env
        ports:
            - ${PORT}:3333
        environment:
            - TOKEN=${TOKEN}
            - PORT=3333
            - MONGODB_ENABLED=${MONGODB_ENABLED}
            - MONGODB_URL=mongodb://mongodb:27017/whatsapp_chats
            - MONGODB_SESSIONS=${MONGODB_SESSIONS}
            - WEBHOOK_ENABLED=${WEBHOOK_ENABLED}
            - WEBHOOK_URL=${WEBHOOK_URL}
            - WEBHOOK_ALLOWED_EVENTS=${WEBHOOK_ALLOWED_EVENTS}
            - WEBHOOK_SEND_MEDIA=${WEBHOOK_SEND_MEDIA}
            - WEBHOOK_TYPE_MEDIA=${WEBHOOK_TYPE_MEDIA}

volumes:
    db: